[package]
name = "cdorg"
version = "0.1.0"
edition = "2021"

[lib]
name = "dacal"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-serialize = "0.3"
clap = { version = "4.0", features = ["derive"] }
rusb = "0.9.1"
