[package]
name = "cdorg"
version = "0.1.0"
edition = "2021"

[lib]
name = "dacal"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
clap = { version = "4.0", features = ["derive"] }
log = "0.4"
pretty_env_logger = "0.4"
rustc-serialize = "0.3"
rusb = "0.9.1"
